[terminal]

shell = "pwsh"


[window]
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "full"
opacity = 1.0

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Bold Italic" }
size = 12.0

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#bfbfbf"

[colors.bright]
black   = "#4d4d4d"
red     = "#ff6e67"
green   = "#5af78e"
yellow  = "#f4f99d"
blue    = "#caa9fa"
magenta = "#ff92d0"
cyan    = "#9aedfe"
white   = "#e6e6e6"

[cursor]
style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true
